name: Build Image using Containerfile
on:
  push:
    paths:
      - docker/**

jobs:
  build:
    name: Build image
    runs-on: dind
    steps:
    - uses: actions/checkout@v4.2.2
    - name: remove all docker images
      run: docker rmi $(docker image ls -aq) --force || true
    - uses: docker/login-action@v3
      with:
        registry: gitea.hnatekmar.xyz
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        cd docker
        docker system prune --all
        docker build . --build-arg BASE=ghcr.io/ublue-os/ucore:stable-nvidia -t gitea.hnatekmar.xyz/public/allmighty-turtle:stable-nvidia
        docker build . --build-arg BASE=ghcr.io/ublue-os/ucore:stable -t gitea.hnatekmar.xyz/public/allmighty-turtle:stable
        docker push --all-tags gitea.hnatekmar.xyz/public/allmighty-turtle

  build-dev:
    name: Build dev image
    runs-on: dind
    steps:
      - uses: actions/checkout@v4.2.2
      - name: remove all docker images
        run: docker rmi $(docker image ls -aq) --force || true
      - uses: docker/login-action@v3
        with:
          registry: gitea.hnatekmar.xyz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: |
          cd docker
          DOCKER_BUILDKIT=1 docker build . -f dev.Dockerfile -t gitea.hnatekmar.xyz/public/workstation:stable
          docker push --all-tags gitea.hnatekmar.xyz/public/workstation
